package com.xenopsconsulting.gamedayapi

import xml.Elem
import java.util.Date

object TestFetchStrategy extends FetchStrategy {

  def fetchEpg(date: Date): Elem = {
    <epg date="20110813" last_modified="2011-08-14T17:52:23Z" display_time_zone="ET">
      <game calendar_event_id="14-288681-2011-08-13" start="2011-08-13T13:07:00-0400"
            id="2011/08/13/anamlb-tormlb-1"
            venue="Rogers Centre"
            game_pk="288681"
            time_zone="ET"
            ampm="PM"
            away_time="10:07"
            away_time_zone="PT"
            away_ampm="AM"
            home_time="1:07"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="1:07"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="1:07"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="14"
            scheduled_innings="9"
            description=""
            away_name_abbrev="LAA"
            home_name_abbrev="TOR"
            away_code="ana"
            away_file_code="ana"
            away_team_id="108"
            away_team_city="LA Angels"
            away_team_name="Angels"
            away_division="W"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="tor"
            home_file_code="tor"
            home_team_id="141"
            home_team_city="Toronto"
            home_team_name="Blue Jays"
            home_division="E"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="3.0"
            home_games_back="13.5"
            away_games_back_wildcard="8.0"
            home_games_back_wildcard="12.5"
            venue_w_chan_loc="CAXX0504"
            gameday="2011_08_13_anamlb_tormlb_1"
            away_win="65"
            away_loss="55"
            home_win="60"
            home_loss="59"
            league="AA"
            time="1:07"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="2"
            home_team_runs="11"
            away_team_hits="4"
            home_team_hits="13"
            away_team_errors="1"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288681-2011-08-13"
                   start="2011-08-13T13:07:00-0400"
                   title="LAA @ TOR"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/anator_288681_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288690-2011-08-13" start="2011-08-13T16:10:00-0400"
            id="2011/08/13/pitmlb-milmlb-1"
            venue="Miller Park"
            game_pk="288690"
            time_zone="ET"
            ampm="PM"
            away_time="4:10"
            away_time_zone="ET"
            away_ampm="PM"
            home_time="3:10"
            home_time_zone="CT"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="4:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="4:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="32"
            scheduled_innings="9"
            description=""
            away_name_abbrev="PIT"
            home_name_abbrev="MIL"
            away_code="pit"
            away_file_code="pit"
            away_team_id="134"
            away_team_city="Pittsburgh"
            away_team_name="Pirates"
            away_division="C"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="mil"
            home_file_code="mil"
            home_team_id="158"
            home_team_city="Milwaukee"
            home_team_name="Brewers"
            home_division="C"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="12.0"
            home_games_back="-"
            away_games_back_wildcard="13.0"
            home_games_back_wildcard=""
            venue_w_chan_loc="USWI0455"
            gameday="2011_08_13_pitmlb_milmlb_1"
            away_win="56"
            away_loss="62"
            home_win="69"
            home_loss="51"
            league="NN"
            time="4:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="0"
            home_team_runs="1"
            away_team_hits="3"
            home_team_hits="8"
            away_team_errors="0"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288690-2011-08-13"
                   start="2011-08-13T16:10:00-0400"
                   title="PIT @ MIL"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/pitmil_288690_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288693-2011-08-13" start="2011-08-13T16:10:00-0400"
            id="2011/08/13/tbamlb-nyamlb-1"
            venue="Yankee Stadium"
            game_pk="288693"
            time_zone="ET"
            ampm="PM"
            away_time="4:10"
            away_time_zone="ET"
            away_ampm="PM"
            home_time="4:10"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="4:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="4:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="3313"
            scheduled_innings="9"
            description=""
            away_name_abbrev="TB"
            home_name_abbrev="NYY"
            away_code="tba"
            away_file_code="tb"
            away_team_id="139"
            away_team_city="Tampa Bay"
            away_team_name="Rays"
            away_division="E"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="nya"
            home_file_code="nyy"
            home_team_id="147"
            home_team_city="NY Yankees"
            home_team_name="Yankees"
            home_division="E"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="9.5"
            home_games_back="1.0"
            away_games_back_wildcard="8.5"
            home_games_back_wildcard="-"
            venue_w_chan_loc="USNY0172"
            gameday="2011_08_13_tbamlb_nyamlb_1"
            away_win="64"
            away_loss="55"
            home_win="72"
            home_loss="46"
            league="AA"
            time="4:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="2"
            home_team_runs="9"
            away_team_hits="5"
            home_team_hits="15"
            away_team_errors="0"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288693-2011-08-13"
                   start="2011-08-13T16:10:00-0400"
                   title="TB @ NYY"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/tbanya_288693_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288694-2011-08-13" start="2011-08-13T16:10:00-0400"
            id="2011/08/13/texmlb-oakmlb-1"
            venue="Oakland Coliseum"
            game_pk="288694"
            time_zone="ET"
            ampm="PM"
            away_time="3:10"
            away_time_zone="CT"
            away_ampm="PM"
            home_time="1:10"
            home_time_zone="PT"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="4:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="4:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="10"
            scheduled_innings="9"
            description=""
            away_name_abbrev="TEX"
            home_name_abbrev="OAK"
            away_code="tex"
            away_file_code="tex"
            away_team_id="140"
            away_team_city="Texas"
            away_team_name="Rangers"
            away_division="W"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="oak"
            home_file_code="oak"
            home_team_id="133"
            home_team_city="Oakland"
            home_team_name="Athletics"
            home_division="W"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="-"
            home_games_back="14.5"
            away_games_back_wildcard=""
            home_games_back_wildcard="19.5"
            venue_w_chan_loc="USCA0791"
            gameday="2011_08_13_texmlb_oakmlb_1"
            away_win="68"
            away_loss="52"
            home_win="53"
            home_loss="66"
            league="AA"
            time="4:10"
            top_inning="N"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="7"
            home_team_runs="1"
            away_team_hits="11"
            home_team_hits="5"
            away_team_errors="0"
            home_team_errors="4">
        <game_media>
            <media type="game" calendar_event_id="14-288694-2011-08-13"
                   start="2011-08-13T16:10:00-0400"
                   title="TEX @ OAK"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/texoak_288694_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288685-2011-08-13" start="2011-08-13T19:05:00-0400"
            id="2011/08/13/detmlb-balmlb-1"
            venue="Oriole Park at Camden Yards"
            game_pk="288685"
            time_zone="ET"
            ampm="PM"
            away_time="7:05"
            away_time_zone="ET"
            away_ampm="PM"
            home_time="7:05"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:05"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:05"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="2"
            scheduled_innings="9"
            description=""
            away_name_abbrev="DET"
            home_name_abbrev="BAL"
            away_code="det"
            away_file_code="det"
            away_team_id="116"
            away_team_city="Detroit"
            away_team_name="Tigers"
            away_division="C"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="bal"
            home_file_code="bal"
            home_team_id="110"
            home_team_city="Baltimore"
            home_team_name="Orioles"
            home_division="E"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="-"
            home_games_back="27.5"
            away_games_back_wildcard=""
            home_games_back_wildcard="26.5"
            venue_w_chan_loc="USMD0018"
            gameday="2011_08_13_detmlb_balmlb_1"
            away_win="64"
            away_loss="55"
            home_win="45"
            home_loss="72"
            league="AA"
            time="7:05"
            top_inning="N"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="6"
            home_team_runs="5"
            away_team_hits="9"
            home_team_hits="8"
            away_team_errors="1"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288685-2011-08-13"
                   start="2011-08-13T19:05:00-0400"
                   title="DET @ BAL"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/detbal_288685_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288688-2011-08-13" start="2011-08-13T19:05:00-0400"
            id="2011/08/13/minmlb-clemlb-1"
            venue="Progressive Field"
            game_pk="288688"
            time_zone="ET"
            ampm="PM"
            away_time="6:05"
            away_time_zone="CT"
            away_ampm="PM"
            home_time="7:05"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:05"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:05"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="5"
            scheduled_innings="9"
            description=""
            away_name_abbrev="MIN"
            home_name_abbrev="CLE"
            away_code="min"
            away_file_code="min"
            away_team_id="142"
            away_team_city="Minnesota"
            away_team_name="Twins"
            away_division="C"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="cle"
            home_file_code="cle"
            home_team_id="114"
            home_team_city="Cleveland"
            home_team_name="Indians"
            home_division="C"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="12.0"
            home_games_back="3.0"
            away_games_back_wildcard="20.5"
            home_games_back_wildcard="11.5"
            venue_w_chan_loc="USOH0195"
            gameday="2011_08_13_minmlb_clemlb_1"
            away_win="52"
            away_loss="67"
            home_win="60"
            home_loss="57"
            league="AA"
            time="7:05"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="1"
            home_team_runs="3"
            away_team_hits="5"
            home_team_hits="10"
            away_team_errors="1"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288688-2011-08-13"
                   start="2011-08-13T19:05:00-0400"
                   title="MIN @ CLE"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/mincle_288688_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288695-2011-08-13" start="2011-08-13T19:05:00-0400"
            id="2011/08/13/wasmlb-phimlb-1"
            venue="Citizens Bank Park"
            game_pk="288695"
            time_zone="ET"
            ampm="PM"
            away_time="7:05"
            away_time_zone="ET"
            away_ampm="PM"
            home_time="7:05"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:05"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:05"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="2681"
            scheduled_innings="9"
            description=""
            away_name_abbrev="WSH"
            home_name_abbrev="PHI"
            away_code="was"
            away_file_code="was"
            away_team_id="120"
            away_team_city="Washington"
            away_team_name="Nationals"
            away_division="E"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="phi"
            home_file_code="phi"
            home_team_id="143"
            home_team_city="Philadelphia"
            home_team_name="Phillies"
            home_division="E"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="21.0"
            home_games_back="-"
            away_games_back_wildcard="12.5"
            home_games_back_wildcard=""
            venue_w_chan_loc="USPA1276"
            gameday="2011_08_13_wasmlb_phimlb_1"
            away_win="57"
            away_loss="62"
            home_win="78"
            home_loss="41"
            league="NN"
            time="7:05"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="3"
            home_team_runs="11"
            away_team_hits="7"
            home_team_hits="9"
            away_team_errors="3"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288695-2011-08-13"
                   start="2011-08-13T19:05:00-0400"
                   title="WSH @ PHI"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/wasphi_288695_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288683-2011-08-13" start="2011-08-13T19:10:00-0400"
            id="2011/08/13/chnmlb-atlmlb-1"
            venue="Turner Field"
            game_pk="288683"
            time_zone="ET"
            ampm="PM"
            away_time="6:10"
            away_time_zone="CT"
            away_ampm="PM"
            home_time="7:10"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="16"
            scheduled_innings="9"
            description=""
            away_name_abbrev="CHC"
            home_name_abbrev="ATL"
            away_code="chn"
            away_file_code="chc"
            away_team_id="112"
            away_team_city="Chi Cubs"
            away_team_name="Cubs"
            away_division="C"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="atl"
            home_file_code="atl"
            home_team_id="144"
            home_team_city="Atlanta"
            home_team_name="Braves"
            home_division="E"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="17.0"
            home_games_back="8.5"
            away_games_back_wildcard="18.0"
            home_games_back_wildcard="-"
            venue_w_chan_loc="USGA0028"
            gameday="2011_08_13_chnmlb_atlmlb_1"
            away_win="52"
            away_loss="68"
            home_win="70"
            home_loss="50"
            league="NN"
            time="7:10"
            top_inning="N"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="8"
            home_team_runs="4"
            away_team_hits="14"
            home_team_hits="12"
            away_team_errors="1"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288683-2011-08-13"
                   start="2011-08-13T19:10:00-0400"
                   title="CHC @ ATL"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/chnatl_288683_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288687-2011-08-13" start="2011-08-13T19:10:00-0400"
            id="2011/08/13/kcamlb-chamlb-1"
            venue="U.S. Cellular Field"
            game_pk="288687"
            time_zone="ET"
            ampm="PM"
            away_time="6:10"
            away_time_zone="CT"
            away_ampm="PM"
            home_time="6:10"
            home_time_zone="CT"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="4"
            scheduled_innings="9"
            description=""
            away_name_abbrev="KC"
            home_name_abbrev="CWS"
            away_code="kca"
            away_file_code="kc"
            away_team_id="118"
            away_team_city="Kansas City"
            away_team_name="Royals"
            away_division="C"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="cha"
            home_file_code="cws"
            home_team_id="145"
            home_team_city="Chi White Sox"
            home_team_name="White Sox"
            home_division="C"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="14.5"
            home_games_back="5.0"
            away_games_back_wildcard="23.0"
            home_games_back_wildcard="13.5"
            venue_w_chan_loc="USIL0225"
            gameday="2011_08_13_kcamlb_chamlb_1"
            away_win="50"
            away_loss="70"
            home_win="59"
            home_loss="60"
            league="AA"
            time="7:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="4"
            home_team_runs="5"
            away_team_hits="11"
            home_team_hits="9"
            away_team_errors="1"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288687-2011-08-13"
                   start="2011-08-13T19:10:00-0400"
                   title="KC @ CWS"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/kcacha_288687_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288691-2011-08-13" start="2011-08-13T19:10:00-0400"
            id="2011/08/13/sdnmlb-cinmlb-1"
            venue="Great American Ball Park"
            game_pk="288691"
            time_zone="ET"
            ampm="PM"
            away_time="4:10"
            away_time_zone="PT"
            away_ampm="PM"
            home_time="7:10"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="2602"
            scheduled_innings="9"
            description=""
            away_name_abbrev="SD"
            home_name_abbrev="CIN"
            away_code="sdn"
            away_file_code="sd"
            away_team_id="135"
            away_team_city="San Diego"
            away_team_name="Padres"
            away_division="W"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="cin"
            home_file_code="cin"
            home_team_id="113"
            home_team_city="Cincinnati"
            home_team_name="Reds"
            home_division="C"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="14.5"
            home_games_back="10.0"
            away_games_back_wildcard="17.5"
            home_games_back_wildcard="11.0"
            venue_w_chan_loc="USOH0188"
            gameday="2011_08_13_sdnmlb_cinmlb_1"
            away_win="53"
            away_loss="68"
            home_win="59"
            home_loss="61"
            league="NN"
            time="7:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="1"
            home_team_runs="13"
            away_team_hits="7"
            home_team_hits="13"
            away_team_errors="0"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288691-2011-08-13"
                   start="2011-08-13T19:10:00-0400"
                   title="SD @ CIN"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/sdncin_288691_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288692-2011-08-13" start="2011-08-13T19:10:00-0400"
            id="2011/08/13/sfnmlb-flomlb-1"
            venue="Sun Life Stadium"
            game_pk="288692"
            time_zone="ET"
            ampm="PM"
            away_time="4:10"
            away_time_zone="PT"
            away_ampm="PM"
            home_time="7:10"
            home_time_zone="ET"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="20"
            scheduled_innings="9"
            description=""
            away_name_abbrev="SF"
            home_name_abbrev="FLA"
            away_code="sfn"
            away_file_code="sf"
            away_team_id="137"
            away_team_city="San Francisco"
            away_team_name="Giants"
            away_division="W"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="flo"
            home_file_code="fla"
            home_team_id="146"
            home_team_city="Florida"
            home_team_name="Marlins"
            home_division="E"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="2.0"
            home_games_back="22.0"
            away_games_back_wildcard="5.0"
            home_games_back_wildcard="13.5"
            venue_w_chan_loc="USFL0316"
            gameday="2011_08_13_sfnmlb_flomlb_1"
            away_win="65"
            away_loss="55"
            home_win="56"
            home_loss="63"
            league="NN"
            time="7:10"
            top_inning="N"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="3"
            home_team_runs="0"
            away_team_hits="6"
            home_team_hits="3"
            away_team_errors="0"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288692-2011-08-13"
                   start="2011-08-13T19:10:00-0400"
                   title="SF @ FLA"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/sfnflo_288692_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288684-2011-08-13" start="2011-08-13T19:15:00-0400"
            id="2011/08/13/colmlb-slnmlb-1"
            venue="Busch Stadium"
            game_pk="288684"
            time_zone="ET"
            ampm="PM"
            away_time="5:15"
            away_time_zone="MT"
            away_ampm="PM"
            home_time="6:15"
            home_time_zone="CT"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="7:15"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="7:15"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="2889"
            scheduled_innings="9"
            description=""
            away_name_abbrev="COL"
            home_name_abbrev="STL"
            away_code="col"
            away_file_code="col"
            away_team_id="115"
            away_team_city="Colorado"
            away_team_name="Rockies"
            away_division="W"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="sln"
            home_file_code="stl"
            home_team_id="138"
            home_team_city="St. Louis"
            home_team_name="Cardinals"
            home_division="C"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="11.5"
            home_games_back="5.0"
            away_games_back_wildcard="14.5"
            home_games_back_wildcard="6.0"
            venue_w_chan_loc="USMO0787"
            gameday="2011_08_13_colmlb_slnmlb_1"
            away_win="56"
            away_loss="65"
            home_win="64"
            home_loss="56"
            league="NN"
            time="7:15"
            top_inning="N"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="6"
            home_team_runs="1"
            away_team_hits="9"
            home_team_hits="6"
            away_team_errors="0"
            home_team_errors="0">
        <game_media>
            <media type="game" calendar_event_id="14-288684-2011-08-13"
                   start="2011-08-13T19:15:00-0400"
                   title="COL @ STL"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/colsln_288684_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288689-2011-08-13" start="2011-08-13T20:10:00-0400"
            id="2011/08/13/nynmlb-arimlb-1"
            venue="Chase Field"
            game_pk="288689"
            time_zone="ET"
            ampm="PM"
            away_time="8:10"
            away_time_zone="ET"
            away_ampm="PM"
            home_time="5:10"
            home_time_zone="MST"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="8:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="8:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="15"
            scheduled_innings="9"
            description=""
            away_name_abbrev="NYM"
            home_name_abbrev="ARI"
            away_code="nyn"
            away_file_code="nym"
            away_team_id="121"
            away_team_city="NY Mets"
            away_team_name="Mets"
            away_division="E"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="ari"
            home_file_code="ari"
            home_team_id="109"
            home_team_city="Arizona"
            home_team_name="D-backs"
            home_division="W"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="20.0"
            home_games_back="-"
            away_games_back_wildcard="11.5"
            home_games_back_wildcard=""
            venue_w_chan_loc="USAZ0166"
            gameday="2011_08_13_nynmlb_arimlb_1"
            away_win="58"
            away_loss="61"
            home_win="67"
            home_loss="53"
            league="NN"
            time="8:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="4"
            home_team_runs="6"
            away_team_hits="8"
            home_team_hits="7"
            away_team_errors="1"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288689-2011-08-13"
                   start="2011-08-13T20:10:00-0400"
                   title="NYM @ ARI"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/nynari_288689_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288682-2011-08-13" start="2011-08-13T22:10:00-0400"
            id="2011/08/13/bosmlb-seamlb-1"
            venue="Safeco Field"
            game_pk="288682"
            time_zone="ET"
            ampm="PM"
            away_time="10:10"
            away_time_zone="ET"
            away_ampm="PM"
            home_time="7:10"
            home_time_zone="PT"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="10:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="10:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="680"
            scheduled_innings="9"
            description=""
            away_name_abbrev="BOS"
            home_name_abbrev="SEA"
            away_code="bos"
            away_file_code="bos"
            away_team_id="111"
            away_team_city="Boston"
            away_team_name="Red Sox"
            away_division="E"
            away_league_id="103"
            away_sport_code="mlb"
            home_code="sea"
            home_file_code="sea"
            home_team_id="136"
            home_team_city="Seattle"
            home_team_name="Mariners"
            home_division="W"
            home_league_id="103"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="-"
            home_games_back="16.0"
            away_games_back_wildcard=""
            home_games_back_wildcard="21.0"
            venue_w_chan_loc="USWA0395"
            gameday="2011_08_13_bosmlb_seamlb_1"
            away_win="73"
            away_loss="45"
            home_win="51"
            home_loss="67"
            league="AA"
            time="10:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="4"
            home_team_runs="5"
            away_team_hits="10"
            home_team_hits="9"
            away_team_errors="0"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288682-2011-08-13"
                   start="2011-08-13T22:10:00-0400"
                   title="BOS @ SEA"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/bossea_288682_preview.jpg"/>
        </game_media>
      </game>
      <game calendar_event_id="14-288686-2011-08-13" start="2011-08-13T22:10:00-0400"
            id="2011/08/13/houmlb-lanmlb-1"
            venue="Dodger Stadium"
            game_pk="288686"
            time_zone="ET"
            ampm="PM"
            away_time="9:10"
            away_time_zone="CT"
            away_ampm="PM"
            home_time="7:10"
            home_time_zone="PT"
            home_ampm="PM"
            game_type="R"
            resume_date=""
            time_aw_lg="10:10"
            aw_lg_ampm="PM"
            tz_aw_lg_gen="ET"
            time_hm_lg="10:10"
            hm_lg_ampm="PM"
            tz_hm_lg_gen="ET"
            venue_id="22"
            scheduled_innings="9"
            description=""
            away_name_abbrev="HOU"
            home_name_abbrev="LAD"
            away_code="hou"
            away_file_code="hou"
            away_team_id="117"
            away_team_city="Houston"
            away_team_name="Astros"
            away_division="C"
            away_league_id="104"
            away_sport_code="mlb"
            home_code="lan"
            home_file_code="la"
            home_team_id="119"
            home_team_city="LA Dodgers"
            home_team_name="Dodgers"
            home_division="W"
            home_league_id="104"
            home_sport_code="mlb"
            day="SAT"
            gameday_sw="P"
            away_games_back="31.0"
            home_games_back="12.0"
            away_games_back_wildcard="32.0"
            home_games_back_wildcard="15.0"
            venue_w_chan_loc="USCA0638"
            gameday="2011_08_13_houmlb_lanmlb_1"
            away_win="38"
            away_loss="82"
            home_win="54"
            home_loss="64"
            league="NN"
            time="10:10"
            top_inning="Y"
            status="Final"
            ind="F"
            inning="9"
            outs="3"
            away_team_runs="1"
            home_team_runs="6"
            away_team_hits="6"
            home_team_hits="9"
            away_team_errors="3"
            home_team_errors="1">
        <game_media>
            <media type="game" calendar_event_id="14-288686-2011-08-13"
                   start="2011-08-13T22:10:00-0400"
                   title="HOU @ LAD"
                   has_mlbtv="true"
                   free="NO"
                   media_state="media_archive"
                   thumbnail="http://mediadownloads.mlb.com/mlbam/preview/houlan_288686_preview.jpg"/>
        </game_media>
      </game>
    </epg>
  }

  def fetchGame(date: Date, team: String): Elem = {
    <game type="R" local_game_time="19:10" game_pk="288682" game_time_et="10:10 PM" gameday_sw="P">
        <team type="home" code="sea" file_code="sea" abbrev="SEA" id="136" name="Seattle" name_full="Seattle Mariners" name_brief="Mariners" w="51" l="67" division_id="200" league_id="103" league="AL"/>
        <team type="away" code="bos" file_code="bos" abbrev="BOS" id="111" name="Boston" name_full="Boston Red Sox" name_brief="Red Sox" w="73" l="45" division_id="201" league_id="103" league="AL"/>
        <stadium id="680" name="Safeco Field" venue_w_chan_loc="USWA0395" location="Seattle, WA"/>
    </game>
  }

  def fetchBoxScore(date: Date, team: String): Elem = {
    <boxscore game_id="2011/08/13/bosmlb-seamlb-1" game_pk="288682" venue_id="680" venue_name="Safeco Field" home_sport_code="mlb" away_team_code="bos" home_team_code="sea" away_id="111" home_id="136" away_fname="Boston Red Sox" home_fname="Seattle Mariners" away_sname="Boston" home_sname="Seattle" date="August 13, 2011" away_wins="73" away_loss="45" home_wins="51" home_loss="67" status_ind="F">
      <linescore away_team_runs="4" home_team_runs="5" away_team_hits="10" home_team_hits="9" away_team_errors="0" home_team_errors="1">
          <inning_line_score away="0" home="5" inning="1"/>
          <inning_line_score away="0" home="0" inning="2"/>
          <inning_line_score away="0" home="0" inning="3"/>
          <inning_line_score away="0" home="0" inning="4"/>
          <inning_line_score away="0" home="0" inning="5"/>
          <inning_line_score away="4" home="0" inning="6"/>
          <inning_line_score away="0" home="0" inning="7"/>
          <inning_line_score away="0" home="0" inning="8"/>
          <inning_line_score away="0" home="x" inning="9"/>
      </linescore>
      <pitching team_flag="away" out="24" h="9" r="5" er="5" bb="1" so="12" hr="2" bf="33" era="3.93">
          <pitcher id="277417" name="Beckett" name_display_first_last="Josh Beckett" pos="P" out="15" bf="23" er="5" r="5" h="8" so="6" hr="2" bb="1" w="9" l="5" sv="0" bs="0" hld="0" era="2.40" note="(L, 9-5)"/>
          <pitcher id="458006" name="Albers" name_display_first_last="Matt Albers" pos="P" out="5" bf="6" er="0" r="0" h="1" so="3" hr="0" bb="0" w="4" l="3" sv="0" bs="2" hld="8" era="2.37"/>
          <pitcher id="462985" name="Morales, F" name_display_first_last="Franklin Morales" pos="P" out="2" bf="2" er="0" r="0" h="0" so="1" hr="0" bb="0" w="0" l="2" sv="0" bs="0" hld="6" era="4.13"/>
          <pitcher id="469686" name="Aceves" name_display_first_last="Alfredo Aceves" pos="P" out="2" bf="2" er="0" r="0" h="0" so="2" hr="0" bb="0" w="8" l="1" sv="1" bs="2" hld="7" era="3.26"/>
      </pitching>
      <batting team_flag="home" ab="32" r="5" h="9" d="2" t="0" hr="2" rbi="5" bb="1" po="27" da="13" so="12" lob="11" avg=".230">
          <batter id="400085" name="Suzuki, I" name_display_first_last="Ichiro Suzuki" pos="RF" bo="100" ab="4" po="1" r="1" a="1" bb="0" sac="0" t="0" sf="0" h="1" e="0" d="0" hbp="0" so="2" hr="1" rbi="1" lob="2" fldg="1.000" sb="0" s_hr="2" s_rbi="28" avg=".267"/>
          <batter id="429711" name="Gutierrez, F" name_display_first_last="Franklin Gutierrez" pos="CF" bo="200" ab="4" po="2" r="1" a="0" bb="0" sac="0" t="0" sf="0" h="2" e="0" d="0" hbp="0" so="1" hr="0" rbi="0" lob="0" fldg="1.000" sb="1" s_hr="1" s_rbi="11" avg=".221"/>
          <batter id="554429" name="Ackley" name_display_first_last="Dustin Ackley" pos="2B" bo="300" ab="4" po="3" r="1" a="3" bb="0" sac="0" t="0" sf="0" h="1" e="0" d="1" hbp="0" so="2" hr="0" rbi="0" lob="2" fldg="1.000" sb="0" s_hr="5" s_rbi="24" avg=".297"/>
          <batter id="455077" name="Carp" name_display_first_last="Mike Carp" pos="1B" bo="400" ab="3" po="7" r="1" a="3" bb="1" sac="0" t="0" sf="0" h="1" e="1" d="0" hbp="0" so="1" hr="0" rbi="2" lob="0" fldg=".909" sb="0" s_hr="4" s_rbi="23" avg=".323"/>
          <batter id="276377" name="Pena" name_display_first_last="Wily Mo Pena" pos="DH" bo="500" ab="4" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="2" hr="0" rbi="0" lob="4" fldg=".000" sb="0" s_hr="5" s_rbi="7" avg=".180"/>
          <batter id="489413" name="Wells, C" name_display_first_last="Casper Wells" pos="LF" bo="600" ab="4" po="2" r="1" a="0" bb="0" sac="0" t="0" sf="0" h="2" e="0" d="0" hbp="0" so="2" hr="1" rbi="2" lob="0" fldg="1.000" sb="0" s_hr="6" s_rbi="20" avg=".274"/>
          <batter id="408036" name="Bard" name_display_first_last="Josh Bard" pos="C" bo="700" ab="3" po="5" r="0" a="1" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="1" hr="0" rbi="0" lob="1" fldg="1.000" sb="0" s_hr="1" s_rbi="6" avg=".212"/>
          <batter id="425904" name="Rodriguez, L" name_display_first_last="Luis Rodriguez" pos="3B" bo="800" ab="3" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="1" fldg=".000" sb="0" s_hr="1" s_rbi="11" avg=".171"/>
          <batter id="333292" name="Wilson, Ja" name_display_first_last="Jack Wilson" pos="SS" bo="900" ab="3" po="5" r="0" a="3" bb="0" sac="0" t="0" sf="0" h="2" e="0" d="1" hbp="0" so="1" hr="0" rbi="0" lob="1" fldg="1.000" sb="0" s_hr="0" s_rbi="9" avg=".244"/>
          <batter id="433587" name="Hernandez, F" name_display_first_last="Felix Hernandez" pos="P" ab="0" po="2" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg="1.000" sb="0" s_hr="0" s_rbi="0" avg=".143"/>
          <batter id="124604" name="Wright, J" name_display_first_last="Jamey Wright" pos="P" ab="0" po="0" r="0" a="1" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg="1.000" sb="0" s_hr="0" s_rbi="0" avg=".000"/>
          <batter id="434181" name="League" name_display_first_last="Brandon League" pos="P" ab="0" po="0" r="0" a="1" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg="1.000" sb="0" s_hr="0" s_rbi="0" avg=".000"/>
        <text_data><![CDATA[<b>BATTING</b><br/><b>2B</b>: Ackley (11, Beckett), Wilson, Ja (8, Beckett).<br/><b>HR</b>: Suzuki, I (2, 1st inning off Beckett, 0 on, 0 out), Wells, C (6, 1st inning off Beckett, 1 on, 1 out).<br/><b>TB</b>: Suzuki, I 4; Gutierrez, F 2; Ackley 2; Carp; Wells, C 5; Wilson, Ja 3.<br/><b>RBI</b>: Suzuki, I (28), Carp 2 (23), Wells, C 2 (20).<br/><b>Runners left in scoring position, 2 out</b>: Pena 2.<br/><b>GIDP</b>: Suzuki, I.<br/><b>Team RISP</b>: 2-for-5.<br/><b>Team LOB</b>: 4.<br/> <br/><b>BASERUNNING</b><br/><b>SB</b>: Gutierrez, F (11, 2nd base off Beckett/Varitek).<br/> <br/><b>FIELDING</b><br/><b>E</b>: Carp (4, pickoff).<br/><b>Outfield assists</b>: Suzuki, I (Ellsbury at home).<br/><b>DP</b>: 4 (Ackley-Wilson, Ja-Carp, Suzuki, I-Bard, Ackley-Carp, Wright, J-Wilson, Ja-Carp).<br/> <br/>]]></text_data>
      </batting>
      <pitching team_flag="home" out="27" h="10" r="4" er="4" bb="3" so="4" hr="2" bf="35" era="3.62">
          <pitcher id="433587" name="Hernandez, F" name_display_first_last="Felix Hernandez" pos="P" out="21" bf="29" er="4" r="4" h="9" so="2" hr="2" bb="2" w="11" l="10" sv="0" bs="0" hld="0" era="3.38" note="(W, 11-10)"/>
          <pitcher id="124604" name="Wright, J" name_display_first_last="Jamey Wright" pos="P" out="3" bf="3" er="0" r="0" h="1" so="0" hr="0" bb="1" w="2" l="3" sv="1" bs="4" hld="14" era="3.44" note="(H, 14)"/>
          <pitcher id="434181" name="League" name_display_first_last="Brandon League" pos="P" out="3" bf="3" er="0" r="0" h="0" so="2" hr="0" bb="0" w="1" l="4" sv="28" bs="4" hld="0" era="2.91" note="(S, 28)"/>
      </pitching>
      <batting team_flag="away" ab="32" r="4" h="10" d="0" t="1" hr="2" rbi="4" bb="3" po="24" da="6" so="4" lob="14" avg=".281">
          <batter id="453056" name="Ellsbury" name_display_first_last="Jacoby Ellsbury" pos="CF" bo="100" ab="3" po="3" r="1" a="0" bb="1" sac="0" t="0" sf="0" h="2" e="0" d="0" hbp="0" so="0" hr="1" rbi="2" lob="0" fldg="1.000" sb="0" s_hr="20" s_rbi="74" avg=".315"/>
          <batter id="408307" name="Crawford" name_display_first_last="Carl Crawford" pos="LF" bo="200" ab="4" po="1" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="1" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="1" fldg="1.000" sb="0" s_hr="7" s_rbi="38" avg=".257"/>
          <batter id="408236" name="Gonzalez, Ad" name_display_first_last="Adrian Gonzalez" pos="1B" bo="300" ab="4" po="5" r="1" a="2" bb="0" sac="0" t="0" sf="0" h="2" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="2" fldg="1.000" sb="0" s_hr="18" s_rbi="92" avg=".351"/>
          <batter id="456030" name="Pedroia" name_display_first_last="Dustin Pedroia" pos="2B" bo="400" ab="4" po="0" r="1" a="0" bb="0" sac="0" t="0" sf="0" h="1" e="0" d="0" hbp="0" so="0" hr="1" rbi="2" lob="3" fldg=".000" sb="0" s_hr="16" s_rbi="62" avg=".310"/>
          <batter id="120074" name="Ortiz" name_display_first_last="David Ortiz" pos="DH" bo="500" ab="2" po="0" r="0" a="0" bb="2" sac="0" t="0" sf="0" h="1" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg=".000" sb="0" s_hr="24" s_rbi="79" avg=".300"/>
          <batter id="150021" name="McDonald, D" name_display_first_last="Darnell McDonald" pos="PR-DH" bo="501" ab="0" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg=".000" sb="0" s_hr="4" s_rbi="15" avg=".182" note="1-"/>
          <batter id="502210" name="Reddick" name_display_first_last="Josh Reddick" pos="RF" bo="600" ab="4" po="1" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="2" hr="0" rbi="0" lob="2" fldg="1.000" sb="0" s_hr="6" s_rbi="25" avg=".314"/>
          <batter id="449107" name="Aviles" name_display_first_last="Mike Aviles" pos="3B" bo="700" ab="3" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="2" e="0" d="0" hbp="0" so="1" hr="0" rbi="0" lob="1" fldg=".000" sb="0" s_hr="5" s_rbi="32" avg=".238"/>
          <batter id="476704" name="Lowrie" name_display_first_last="Jed Lowrie" pos="PH" bo="701" ab="1" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="1" hr="0" rbi="0" lob="0" fldg=".000" sb="0" s_hr="4" s_rbi="26" avg=".263" note="a-"/>
          <batter id="123660" name="Varitek" name_display_first_last="Jason Varitek" pos="C" bo="800" ab="4" po="12" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="4" fldg="1.000" sb="0" s_hr="7" s_rbi="23" avg=".224"/>
          <batter id="340192" name="Scutaro" name_display_first_last="Marco Scutaro" pos="SS" bo="900" ab="3" po="1" r="1" a="3" bb="0" sac="0" t="1" sf="0" h="1" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="1" fldg="1.000" sb="0" s_hr="5" s_rbi="26" avg=".279"/>
          <batter id="277417" name="Beckett" name_display_first_last="Josh Beckett" pos="P" ab="0" po="1" r="0" a="1" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg="1.000" sb="0" s_hr="0" s_rbi="0" avg=".000"/>
          <batter id="458006" name="Albers" name_display_first_last="Matt Albers" pos="P" ab="0" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg=".000" sb="0" s_hr="0" s_rbi="0" avg=".000"/>
          <batter id="462985" name="Morales, F" name_display_first_last="Franklin Morales" pos="P" ab="0" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg=".000" sb="0" s_hr="0" s_rbi="0" avg=".000"/>
          <batter id="469686" name="Aceves" name_display_first_last="Alfredo Aceves" pos="P" ab="0" po="0" r="0" a="0" bb="0" sac="0" t="0" sf="0" h="0" e="0" d="0" hbp="0" so="0" hr="0" rbi="0" lob="0" fldg=".000" sb="0" s_hr="0" s_rbi="0" avg=".000"/>
        <note><![CDATA[a-Struck out for Aviles in the 9th. <br/>1-Ran for Ortiz in the 8th. ]]></note>
        <text_data><![CDATA[<b>BATTING</b><br/><b>3B</b>: Scutaro (1, Hernandez, F).<br/><b>HR</b>: Ellsbury (20, 6th inning off Hernandez, F, 1 on, 0 out), Pedroia (16, 6th inning off Hernandez, F, 1 on, 1 out).<br/><b>TB</b>: Ellsbury 5; Crawford; Gonzalez, Ad 2; Pedroia 4; Ortiz; Aviles 2; Scutaro 3.<br/><b>RBI</b>: Ellsbury 2 (74), Pedroia 2 (62).<br/><b>Runners left in scoring position, 2 out</b>: Varitek.<br/><b>GIDP</b>: Scutaro; Crawford; Pedroia.<br/><b>Team RISP</b>: 2-for-5.<br/><b>Team LOB</b>: 4.<br/> <br/><b>BASERUNNING</b><br/><b>CS</b>: McDonald, D (3, 2nd base by Wright, J/Bard).<br/> <br/><b>FIELDING</b><br/><b>DP</b>: (Gonzalez, Ad-Scutaro-Gonzalez, Ad).<br/> <br/>]]></text_data>
      </batting>
      <game_info><![CDATA[<b>Pitches-strikes</b>: Beckett 99-63, Albers 26-18, Morales, F 6-5, Aceves 10-7, Hernandez, F 107-73, Wright, J 18-8, League 14-9.<br/><b>Groundouts-flyouts</b>: Beckett 6-2, Albers 0-2, Morales, F 0-1, Aceves 0-0, Hernandez, F 7-4, Wright, J 1-0, League 1-0.<br/><b>Batters faced</b>: Beckett 23, Albers 6, Morales, F 2, Aceves 2, Hernandez, F 29, Wright, J 3, League 3.<br/><b>Ejections</b>: Boston Red Sox Manager Terry Francona ejected by HP umpire Mark Ripperger (4th).<br/><b>Umpires</b>: HP: Mark Ripperger. 1B: Brian O'Nora. 2B: Alfonso Marquez. 3B: Ed Hickox.<br/><b>Weather</b>: 68 degrees, partly cloudy.<br/><b>Wind</b>: 4 mph, Out to CF.<br/><b>T</b>: 3:03.<br/><b>Att</b>: 41,326.<br/>]]></game_info>
    </boxscore>
  }

}